import logging
import hashlib
import re
import time
from typing import Any, Dict, Iterable, Optional

try:
    from cloakbrowser import launch, launch_persistent_context
except ImportError:
    launch = None
    launch_persistent_context = None

from drivers.lib.network_monitor import wait_for_network_idle_custom
from engines.bot.challenge_solver import ChallengeSolver

logger = logging.getLogger(__name__)

class CloakBrowserDriver:
    """
    CloakBrowser browser client for high-stealth web scraping.
    Built around a source-patched Chromium binary and humanized behavioral layer.
    """
    def __init__(
        self,
        headless: bool = True,
        proxy: Optional[Dict[str, str]] = None,
        user_data_dir: Optional[str] = None,
        identity_profile: Optional[Dict] = None
    ):
        """
        Initializes the CloakBrowser driver.
        
        Args:
            headless: Run browser in headless mode.
            proxy: Dictionary with proxy details (server, username, password).
            user_data_dir: Path to persist browser session/cookies.
            identity_profile: Profile generated by BrowserForgeManager containing user_agent, viewport, etc.
        """
        self.headless = headless
        self.proxy = proxy
        self.user_data_dir = user_data_dir
        self.identity_profile = identity_profile or {}

    def fetch(self, url: str, actions: Optional[Iterable[Any]] = None) -> str:
        """
        Fetches the raw HTML of a URL using CloakBrowser.
        Returns the rendered HTML content.
        """
        # Determine proxy config
        proxy_config = None
        target_proxy = self.identity_profile.get("proxy") or self.proxy
        if target_proxy and "server" in target_proxy:
            proxy_config = {
                "server": target_proxy["server"],
                "username": target_proxy.get("username", ""),
                "password": target_proxy.get("password", "")
            }

        target_headless = self.identity_profile.get("headless", self.headless)
        target_user_data_dir = self.identity_profile.get("user_data_dir", self.user_data_dir)
        viewport = self.identity_profile.get("viewport")

        # Extract timezone & locale from identity profile
        timezone = self.identity_profile.get("timezone_id")
        locale = self.identity_profile.get("locale")

        logger.info(f"Launching CloakBrowser (headless={target_headless}) to fetch {url}...")

        # Reset event loop to avoid conflict with other drivers
        try:
            import asyncio
            new_loop = asyncio.new_event_loop()
            asyncio.set_event_loop(new_loop)
        except Exception as e:
            logger.debug(f"Failed to reset asyncio loop in CloakBrowserDriver: {e}")

        if target_user_data_dir:
            if launch_persistent_context is None:
                raise RuntimeError("cloakbrowser is not installed")
            
            # Prepare arguments for launch_persistent_context
            launch_kwargs = {
                "user_data_dir": target_user_data_dir,
                "headless": target_headless,
                "humanize": self.identity_profile.get("humanize", True),
            }
            if proxy_config:
                launch_kwargs["proxy"] = proxy_config
            if viewport:
                launch_kwargs["viewport"] = viewport
            if locale:
                launch_kwargs["locale"] = locale
            if timezone:
                launch_kwargs["timezone"] = timezone

            context = launch_persistent_context(**launch_kwargs)
            page = context.pages[0] if context.pages else context.new_page()
            browser = None
        else:
            if launch is None:
                raise RuntimeError("cloakbrowser is not installed")
                
            launch_kwargs = {
                "headless": target_headless,
                "humanize": self.identity_profile.get("humanize", True),
            }
            if proxy_config:
                launch_kwargs["proxy"] = proxy_config
            if locale:
                launch_kwargs["locale"] = locale
            if timezone:
                launch_kwargs["timezone"] = timezone

            browser = launch(**launch_kwargs)
            
            context_kwargs = {}
            if viewport:
                context_kwargs["viewport"] = viewport
                
            context = browser.new_context(**context_kwargs)
            page = context.new_page()

        try:
            logger.info("Navigating to URL...")
            page.goto(url, wait_until="domcontentloaded", timeout=60000)

            # Integrate ChallengeSolver to resolve any anti-bot screens
            try:
                ChallengeSolver.solve_challenge_sync(
                    url=url,
                    evaluate_fn=lambda script: page.evaluate(script),
                    mouse_move_fn=lambda x, y: page.mouse.move(x, y),
                    mouse_click_fn=lambda x, y: page.mouse.click(x, y),
                    scroll_down_fn=lambda amount: page.evaluate(f"window.scrollBy(0, {amount})"),
                    scroll_up_fn=lambda amount: page.evaluate(f"window.scrollBy(0, -{amount})"),
                    sleep_fn=time.sleep,
                    max_attempts=120
                )
            except Exception as e:
                logger.warning(f"ChallengeSolver verification failed or encountered error: {e}")

            # Wait for network stabilization using custom logic
            try:
                wait_for_network_idle_custom(page, quiet_period=5.0, hard_timeout=120.0)
            except Exception as e:
                logger.warning(f"Custom network wait failed: {e}")

            self._run_actions(page, actions or [])

            # Extract the rendered HTML content
            html_content = page.content()
            return html_content

        except Exception as e:
            logger.error(f"CloakBrowser extraction failed for {url}: {e}")
            raise
        finally:
            try:
                if target_user_data_dir:
                    context.close()
                else:
                    if context:
                        context.close()
                    if browser:
                        browser.close()
            except Exception as close_err:
                logger.warning(f"Error closing CloakBrowser: {close_err}")

    def _run_actions(self, page, actions: Iterable[Any]) -> None:
        actions = list(actions or [])
        if not actions:
            return

        logger.info("[CloakBrowser] Running %s post-load actions", len(actions))
        for raw_action in actions:
            action = self._normalize_action(raw_action)
            kind = str(action.get("kind", "")).strip().lower()
            selector = action.get("selector")
            value = action.get("value")
            timeout_ms = int(action.get("timeout_ms", 5000))
            optional = bool(action.get("optional", False))

            try:
                if kind == "wait":
                    time.sleep(self._coerce_wait_seconds(value=value, timeout_ms=timeout_ms))
                elif kind == "click":
                    self._click_first(page, selector, timeout_ms=timeout_ms)
                elif kind == "scroll":
                    self._scroll(page, value)
                elif kind == "repeat_click_until_stable":
                    self._repeat_click_until_stable(page, action)
                elif kind == "repeat_click_append":
                    self._repeat_click_append(page, action)
                elif kind == "scroll_until_stable":
                    self._scroll_until_stable(page, action)
                elif kind in {"extract_html", "dismiss_banner", "solve_challenge", "wait_for_selector", "type"}:
                    logger.debug("[CloakBrowser] Action '%s' is not implemented for CloakBrowser yet.", kind)
                else:
                    raise ValueError(f"Unsupported CloakBrowser action kind: {kind}")
            except Exception as exc:
                if optional:
                    logger.warning("[CloakBrowser] Optional action '%s' failed: %s", kind, exc)
                    continue
                raise

    def _normalize_action(self, raw_action: Any) -> Dict[str, Any]:
        if hasattr(raw_action, "to_dict"):
            return raw_action.to_dict()
        if isinstance(raw_action, dict):
            return raw_action
        raise TypeError(f"Unsupported CloakBrowser action payload: {type(raw_action)!r}")

    def _coerce_wait_seconds(self, *, value: Optional[str], timeout_ms: int) -> float:
        if value in (None, ""):
            return max(timeout_ms / 1000.0, 0.25)
        try:
            return max(float(value), 0.0)
        except (TypeError, ValueError):
            return max(timeout_ms / 1000.0, 0.25)

    def _repeat_click_until_stable(self, page, action: Dict[str, Any]) -> None:
        selector = action.get("selector")
        if not selector:
            raise ValueError("repeat_click_until_stable requires a selector")
        max_iterations = max(int(action.get("max_iterations", 10)), 1)
        wait_seconds = max(int(action.get("wait_ms", 1500)) / 1000.0, 0.25)
        previous_hash = None
        stable_hits = 0

        for _ in range(max_iterations):
            before_hash = self._dom_hash(page)
            if not self._click_first(page, selector, optional=True):
                break
            time.sleep(wait_seconds)
            try:
                wait_for_network_idle_custom(page, quiet_period=1.0, hard_timeout=10.0)
            except Exception:
                pass
            after_hash = self._dom_hash(page)
            stable_hits = stable_hits + 1 if after_hash in {before_hash, previous_hash} else 0
            previous_hash = after_hash
            if stable_hits >= 1:
                break

    def _repeat_click_append(self, page, action: Dict[str, Any]) -> None:
        selector = action.get("selector")
        if not selector:
            raise ValueError("repeat_click_append requires a selector")
        max_iterations = max(int(action.get("max_iterations", 10)), 1)
        wait_seconds = max(int(action.get("wait_ms", 1500)) / 1000.0, 0.25)
        previous_size = len(page.content() or "")

        for _ in range(max_iterations):
            if not self._click_first(page, selector, optional=True):
                break
            time.sleep(wait_seconds)
            current_size = len(page.content() or "")
            if current_size <= previous_size:
                break
            previous_size = current_size

    def _scroll_until_stable(self, page, action: Dict[str, Any]) -> None:
        max_scrolls = max(int(action.get("max_iterations", 10)), 1)
        wait_seconds = max(int(action.get("wait_ms", 1500)) / 1000.0, 0.25)
        scroll_step_px = int(action.get("scroll_step_px", 800))
        previous_hash = None
        stable_hits = 0

        for _ in range(max_scrolls):
            page.evaluate(f"window.scrollBy(0, {scroll_step_px});")
            time.sleep(wait_seconds)
            current_hash = self._dom_hash(page)
            stable_hits = stable_hits + 1 if current_hash == previous_hash else 0
            previous_hash = current_hash
            if stable_hits >= 1:
                break

    def _scroll(self, page, value: Optional[str]) -> None:
        direction = str(value or "bottom").strip().lower()
        if direction in {"bottom", "down"}:
            page.evaluate("window.scrollTo(0, document.body.scrollHeight);")
        elif direction in {"top", "up"}:
            page.evaluate("window.scrollTo(0, 0);")
        else:
            try:
                amount = int(float(direction))
            except ValueError:
                amount = 600
            page.evaluate(f"window.scrollBy(0, {amount});")
        time.sleep(0.5)

    def _click_first(self, page, selector: Optional[str], *, timeout_ms: int = 5000, optional: bool = False) -> bool:
        if not selector:
            if optional:
                return False
            raise ValueError("click action requires a selector")

        for candidate in self._split_selectors(selector):
            try:
                locator = self._locator_for_selector(page, candidate)
                if locator.count() > 0 and locator.first.is_visible(timeout=timeout_ms):
                    locator.first.click(timeout=timeout_ms)
                    return True
            except Exception:
                continue
        if optional:
            return False
        raise RuntimeError(f"No clickable element found for selector: {selector}")

    def _locator_for_selector(self, page, selector: str):
        contains_match = re.fullmatch(r"([a-zA-Z0-9_-]+):contains\(['\"](.+)['\"]\)", selector)
        if contains_match:
            tag, text = contains_match.groups()
            return page.locator(tag).filter(has_text=text)
        return page.locator(selector)

    def _split_selectors(self, selector: str) -> Iterable[str]:
        return [part.strip() for part in re.split(r"\s*,\s*", selector) if part.strip()]

    def _dom_hash(self, page) -> str:
        html = page.content() or ""
        return hashlib.sha256(html.encode("utf-8", errors="ignore")).hexdigest()
