import logging
from typing import Any, Dict, Iterable, Optional

try:
    from patchright.sync_api import sync_playwright
except Exception:  # pragma: no cover - optional dependency
    sync_playwright = None
from drivers.lib.network_monitor import wait_for_network_idle_custom

logger = logging.getLogger(__name__)

class PatchrightDriver:
    """
    Patchright browser client for stealth web scraping.
    Acts as an engine-patched drop-in replacement for Playwright.
    Primary driver for Sprint 2 (combining identity + persistent sessions).
    """
    def __init__(
        self,
        headless: bool = False,
        proxy: Optional[Dict[str, str]] = None,
        user_data_dir: Optional[str] = None,
        identity_profile: Optional[Dict] = None
    ):
        """
        Initializes the Patchright driver.
        
        Args:
            headless: Run browser in headless mode. 
            proxy: Dictionary with proxy details (server, username, password).
            user_data_dir: Path to persist browser session/cookies.
            identity_profile: Profile generated by BrowserForgeManager containing user_agent, viewport, etc.
        """
        self.headless = headless
        self.proxy = proxy
        self.user_data_dir = user_data_dir
        self.identity_profile = identity_profile or {}

    def fetch(self, url: str, actions: Optional[Iterable[Any]] = None) -> str:
        """
        Fetches the raw HTML of a URL using Patchright.
        Returns the rendered HTML content.
        """
        if actions:
            logger.info("[Patchright] Actions requested but not yet implemented; proceeding with plain fetch.")
        # Determine proxy config
        proxy_config = None
        target_proxy = self.identity_profile.get("proxy") or self.proxy
        if target_proxy and "server" in target_proxy:
            proxy_config = {
                "server": target_proxy["server"],
                "username": target_proxy.get("username", ""),
                "password": target_proxy.get("password", "")
            }

        target_headless = self.identity_profile.get("headless", self.headless)
        target_user_data_dir = self.identity_profile.get("user_data_dir", self.user_data_dir)
        user_agent = self.identity_profile.get("user_agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
        viewport = self.identity_profile.get("viewport", {"width": 1920, "height": 1080})
        extra_headers = self.identity_profile.get("headers", {})

        logger.info(f"Launching Patchright (headless={target_headless}) to fetch {url}...")
        
        try:
            if sync_playwright is None:
                raise RuntimeError("patchright is not installed")
            
            # Reset event loop to avoid conflict with other drivers
            try:
                import asyncio
                new_loop = asyncio.new_event_loop()
                asyncio.set_event_loop(new_loop)
            except Exception as e:
                logger.debug(f"Failed to reset asyncio loop in PatchrightDriver: {e}")

            with sync_playwright() as p:
                browser_args = [
                    "--disable-blink-features=AutomationControlled",
                    "--disable-infobars",
                    f"--window-size={viewport.get('width', 1920)},{viewport.get('height', 1080)}"
                ]

                if target_user_data_dir:
                    context = p.chromium.launch_persistent_context(
                        user_data_dir=target_user_data_dir,
                        channel="chrome",
                        headless=target_headless,
                        proxy=proxy_config,
                        no_viewport=True,
                        user_agent=user_agent,
                        extra_http_headers=extra_headers,
                        args=browser_args
                    )
                    page = context.pages[0] if context.pages else context.new_page()
                else:
                    browser = p.chromium.launch(
                        channel="chrome",
                        headless=target_headless,
                        proxy=proxy_config,
                        args=browser_args
                    )
                    context = browser.new_context(
                        viewport=viewport,
                        user_agent=user_agent,
                        extra_http_headers=extra_headers
                    )
                    page = context.new_page()

                # Navigate to the target page
                logger.info("Navigating to URL...")
                page.goto(url, wait_until="domcontentloaded", timeout=60000)
                
                # Wait for network to stabilize using custom logic
                try:
                    wait_for_network_idle_custom(page, quiet_period=5.0, hard_timeout=200.0)
                except Exception as e:
                    logger.warning(f"Custom network wait failed: {e}")
                
                # Extract fully rendered HTML for Part 1 text extraction
                html_content = page.content()
                
                # Graceful shutdown
                if self.user_data_dir:
                    context.close()
                else:
                    browser.close()
                    
                return html_content

        except Exception as e:
            logger.error(f"Patchright extraction failed for {url}: {e}")
            raise
