import logging
from typing import Any, Dict, Iterable, Optional

try:
    from playwright_stealth import Stealth
    from playwright.sync_api import sync_playwright
except Exception:  # pragma: no cover - optional dependency
    Stealth = None
    sync_playwright = None
from drivers.lib.network_monitor import wait_for_network_idle_custom

logger = logging.getLogger(__name__)

class PlaywrightDriver:
    """
    Standard Playwright browser client combined with the playwright-stealth plugin.
    Acts as the foundational browser automation layer capable of passing basic bot checks.
    """
    def __init__(
        self,
        headless: bool = True,
        proxy: Optional[Dict[str, str]] = None,
        user_data_dir: Optional[str] = None,
        identity_profile: Optional[Dict] = None
    ):
        """
        Initializes the Playwright driver.
        
        Args:
            headless: Run browser in headless mode.
            proxy: Dictionary with proxy details (server, username, password).
            user_data_dir: Path to persist browser session/cookies.
            identity_profile: Profile generated by BrowserForgeManager containing user_agent, viewport, etc.
        """
        self.headless = headless
        self.proxy = proxy
        self.user_data_dir = user_data_dir
        self.identity_profile = identity_profile or {}

    def fetch(self, url: str, actions: Optional[Iterable[Any]] = None) -> str:
        """
        Fetches the raw HTML of a URL using Playwright + Stealth.
        Returns the rendered HTML content.
        """
        if actions:
            logger.info("[Playwright] Actions requested but not yet implemented; proceeding with plain fetch.")
        # Determine proxy config
        proxy_config = None
        target_proxy = self.identity_profile.get("proxy") or self.proxy
        if target_proxy and "server" in target_proxy:
            proxy_config = {
                "server": target_proxy["server"],
                "username": target_proxy.get("username", ""),
                "password": target_proxy.get("password", "")
            }

        target_headless = self.identity_profile.get("headless", self.headless)
        target_user_data_dir = self.identity_profile.get("user_data_dir", self.user_data_dir)
        user_agent = self.identity_profile.get("user_agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
        viewport = self.identity_profile.get("viewport", {"width": 1920, "height": 1080})
        extra_headers = self.identity_profile.get("headers", {})

        logger.info(f"Launching Playwright (headless={target_headless}) to fetch {url}...")
        
        try:
            if Stealth is None or sync_playwright is None:
                raise RuntimeError("playwright and playwright-stealth are not installed")
            
            # Reset event loop to avoid conflict with other drivers
            try:
                import asyncio
                new_loop = asyncio.new_event_loop()
                asyncio.set_event_loop(new_loop)
            except Exception as e:
                logger.debug(f"Failed to reset asyncio loop in PlaywrightDriver: {e}")

            with Stealth().use_sync(sync_playwright()) as p:
                
                browser_args = [
                    "--disable-blink-features=AutomationControlled",
                    "--disable-infobars"
                ]

                if target_user_data_dir:
                    context = p.chromium.launch_persistent_context(
                        user_data_dir=target_user_data_dir,
                        headless=target_headless,
                        proxy=proxy_config,
                        args=browser_args,
                        viewport=viewport,
                        user_agent=user_agent,
                        extra_http_headers=extra_headers
                    )
                    page = context.pages[0] if context.pages else context.new_page()
                else:
                    browser = p.chromium.launch(
                        headless=target_headless,
                        proxy=proxy_config,
                        args=browser_args
                    )
                    context = browser.new_context(
                        viewport=viewport,
                        user_agent=user_agent,
                        extra_http_headers=extra_headers
                    )
                    page = context.new_page()

                logger.info("Navigating to URL...")
                # Use domcontentloaded to ensure the DOM is ready for text extraction
                page.goto(url, wait_until="domcontentloaded", timeout=60000)
                
                # Wait for network to stabilize using custom logic
                try:
                    wait_for_network_idle_custom(page, quiet_period=5.0, hard_timeout=200.0)
                except Exception as e:
                    logger.warning(f"Custom network wait failed: {e}")
                
                # Extract the rendered DOM
                html_content = page.content()
                
                # Cleanup
                if self.user_data_dir:
                    context.close()
                else:
                    browser.close()
                    
                return html_content

        except Exception as e:
            logger.error(f"Playwright extraction failed for {url}: {e}")
            raise
